name:                nest-exporter
version:             0.1.0.0
github:              "ThomWright/nest-exporter"
license:             BSD3
author:              "Thom Wright"
maintainer:          "git@thomwright.co.uk"
copyright:           "2018 Thom Wright"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ThomWright/nest-exporter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  nest-exporter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nest-exporter

tests:
  nest-exporter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nest-exporter
